---
- name: Variables example
  hosts: local

  vars:
    directory_name: /tmp/student
    file_name: information.txt

  tasks:
    - name: Create directory
      ansible.builtin.file:
        path: "{{ directory_name }}"
        state: directory
    
    - name: Create file
      ansible.builtin.file:
        path: "{{ directory_name }}/{{ file_name }}"
        state: touch